# Generated by Django 5.0.6 on 2024-05-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('vehicle_number', models.CharField(max_length=100)),
                ('kilometers', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='vehicle_images')),
                ('status', models.CharField(max_length=100)),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('customer_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customercard')),
            ],
        ),
    ]
