# Generated by Django 5.0.6 on 2024-05-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercard',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
